# Generated by Django 5.1.3 on 2024-12-02 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postimage_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 2, 21, 28, 4, 929909)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 12, 2, 19, 28, 32, 625207, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
