# Generated by Django 5.1.3 on 2025-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='outline',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
