# Generated by Django 5.1.3 on 2024-12-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project images'},
        ),
    ]
