# Generated by Django 5.1.3 on 2025-01-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outline',
            field=models.CharField(max_length=300),
        ),
    ]
